services:
  db:
    image: postgres:15
    container_name: weout-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build: ./backend
    container_name: weout-backend
    ports:
      - "${NODE_PORT}:${NODE_PORT}"  # App Node.js
      - "5553:5553"  # Prisma Studio
    volumes:
      - ./backend:/app
    environment:
      - NODE_PORT=${NODE_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      db:
        condition: service_healthy

  


volumes:
  pgdata: